config/routes.rb
Rails.application.routes.draw do

  get 'story_plot/index'

  get 'character_name/index'

  resources :last_names, except: :show
  resources :first_names, except: :show
  resources :places, except: :show
  resources :situations, except: :show
  resources :characters, except: :show

  root to: 'home#index'

end

app/views/partials/_flash_messages.html.erb
<% flash.each do |type, information| %>
  <div class="<%= flash_class(type) %>">
    <%= information %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<div id="footer">
  <h6 align="center"><%= raw t('footer.copyright') %><%= link_to 'https://github.com/rubyandcoffee/story_generator' do %><%= image_tag 'github.png' %><% end %></h6>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Story Generator', root_url, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Plot Generator', story_plot_index_path %></li>
        <li><%= link_to 'Character Name Generator', character_name_index_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All Characters', characters_path %></li>
            <li><%= link_to 'All Situations', situations_path %></li>
            <li><%= link_to 'All Places', places_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'All First Names', first_names_path %></li>
            <li><%= link_to 'All Last Names', last_names_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>