config/routes.rb
Rails.application.routes.draw do

  get 'story_plot/index'

  get 'character_name/index'

  resources :last_names, except: :show
  resources :first_names, except: :show
  resources :places, except: :show
  resources :situations, except: :show
  resources :characters, except: :show

  root to: 'home#index'

end

app/models/first_name.rb
class FirstName < ApplicationRecord
end

app/controllers/first_names_controller.rb
class FirstNamesController < ApplicationController
  before_action :set_first_name, only: [:edit, :update, :destroy]

  # GET /first_names
  # GET /first_names.json
  def index
    @first_names = FirstName.order('name')
  end

  # GET /first_names/new
  def new
    @first_name = FirstName.new
  end

  # GET /first_names/1/edit
  def edit
  end

  # POST /first_names
  # POST /first_names.json
  def create
    @first_name = FirstName.new(first_name_params)

    respond_to do |format|
      if @first_name.save
        format.html { redirect_to first_names_url, notice: "First name '#{@first_name.name}' was successfully created." }
        format.json { render :index, status: :created, location: first_names_url }
      else
        format.html { render :new }
        format.json { render json: @first_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /first_names/1
  # PATCH/PUT /first_names/1.json
  def update
    respond_to do |format|
      if @first_name.update(first_name_params)
        format.html { redirect_to first_names_url, notice: "First name '#{@first_name.name}' was successfully updated." }
        format.json { render :index, status: :ok, location: first_names_url }
      else
        format.html { render :edit }
        format.json { render json: @first_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_names/1
  # DELETE /first_names/1.json
  def destroy
    @first_name.destroy
    respond_to do |format|
      format.html { redirect_to first_names_url, notice: "First name '#{@first_name.name}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first_name
      @first_name = FirstName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_name_params
      params.require(:first_name).permit(:name)
    end
end

app/helpers/first_names_helper.rb
module FirstNamesHelper
end

app/views/first_names/_form.html.erb
<%= form_for(first_name) do |f| %>
  <% if first_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(first_name.errors.count, "error") %> prohibited this first_name from being saved:</h2>

      <ul>
      <% first_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Lucy' %>
  </div>

  <%= f.submit class: 'btn btn-success' %>

<% end %>

app/views/first_names/edit.html.erb
<div align="center">
  <h1>Editing First Name</h1>

  <%= render 'form', first_name: @first_name %>

</div>

app/views/first_names/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>First Names</h1>
      <%= link_to 'New First Name', new_first_name_path, class: 'btn btn-success' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h2>Name</h2>
    </div>
    <div class="col-md-6">
      <h2>Actions</h2>
    </div>
  </div>

  <% @first_names.each do |first_name| %>
  <div class="row">
    <div class="col-md-6">
      <p><%= first_name.name %></p>
    </div>
    <div class="col-md-6">
      <div class="btn-group" role="group">
        <%= link_to 'Edit', edit_first_name_path(first_name), type: 'button', class: 'btn btn-info' %>
        <%= link_to 'Destroy', first_name, method: :delete, data: { confirm: 'Are you sure?' } , type: 'button', class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/first_names/new.html.erb
<div align="center">
  <h1>New First Name</h1>

  <%= render 'form', first_name: @first_name %>
</div>