config/routes.rb
Rails.application.routes.draw do

  get 'story_plot/index'

  get 'character_name/index'

  resources :last_names, except: :show
  resources :first_names, except: :show
  resources :places, except: :show
  resources :situations, except: :show
  resources :characters, except: :show

  root to: 'home#index'

end

app/models/character.rb
class Character < ApplicationRecord
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.order('character_type')
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to characters_url, notice: "Character '#{@character.name}' was successfully created." }
        format.json { render :index, status: :created, location: characters_url }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to characters_url, notice: "Character '#{@character.name}' was successfully updated." }
        format.json { render :index, status: :ok, location: characters_url }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character '#{@character.name}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :character_type)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(character) do |f| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'woman' %>
  </div>
  <div class="form-group">
    <%= f.label :character_type %>
    <%= f.text_field :character_type, class: 'form-control', placeholder: 'Gender' %>
  </div>

  <%= f.submit class: 'btn btn-success' %>

<% end %>

app/views/characters/edit.html.erb
<div align="center">
  <h1>Editing Character</h1>

  <%= render 'form', character: @character %>

</div>

app/views/characters/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Characters</h1>
      <%= link_to 'New Character', new_character_path, class: 'btn btn-success' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h2>Name</h2>
    </div>
    <div class="col-md-4">
      <h2>Character type</h2>
    </div>
    <div class="col-md-4">
      <h2>Actions</h2>
    </div>
  </div>

  <% @characters.each do |character| %>
  <div class="row">
    <div class="col-md-4">
      <p><%= character.name %></p>
    </div>
    <div class="col-md-4">
      <p><%= character.character_type %></p>
    </div>
    <div class="col-md-4">
      <div class="btn-group" role="group">
        <%= link_to 'Edit', edit_character_path(character), type: 'button', class: 'btn btn-info' %>
        <%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } , type: 'button', class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/characters/new.html.erb
<div align="center">
  <h1>New Character</h1>

  <%= render 'form', character: @character %>
</div>