config/routes.rb
Rails.application.routes.draw do

  get 'story_plot/index'

  get 'character_name/index'

  resources :last_names, except: :show
  resources :first_names, except: :show
  resources :places, except: :show
  resources :situations, except: :show
  resources :characters, except: :show

  root to: 'home#index'

end

app/models/last_name.rb
class LastName < ApplicationRecord
end

app/controllers/last_names_controller.rb
class LastNamesController < ApplicationController
  before_action :set_last_name, only: [:edit, :update, :destroy]

  # GET /last_names
  # GET /last_names.json
  def index
    @last_names = LastName.order('name')
  end

  # GET /last_names/new
  def new
    @last_name = LastName.new
  end

  # GET /last_names/1/edit
  def edit
  end

  # POST /last_names
  # POST /last_names.json
  def create
    @last_name = LastName.new(last_name_params)

    respond_to do |format|
      if @last_name.save
        format.html { redirect_to last_names_url, notice: "Last name '#{@last_name.name}' was successfully created." }
        format.json { render :index, status: :created, location: last_names_url }
      else
        format.html { render :new }
        format.json { render json: @last_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /last_names/1
  # PATCH/PUT /last_names/1.json
  def update
    respond_to do |format|
      if @last_name.update(last_name_params)
        format.html { redirect_to last_names_url, notice: "Last name '#{@last_name.name}' was successfully updated." }
        format.json { render :index, status: :ok, location: last_names_url }
      else
        format.html { render :edit }
        format.json { render json: @last_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /last_names/1
  # DELETE /last_names/1.json
  def destroy
    @last_name.destroy
    respond_to do |format|
      format.html { redirect_to last_names_url, notice: "Last name '#{@last_name.name}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_last_name
      @last_name = LastName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def last_name_params
      params.require(:last_name).permit(:name)
    end
end

app/helpers/last_names_helper.rb
module LastNamesHelper
end

app/views/last_names/_form.html.erb
<%= form_for(last_name) do |f| %>
  <% if last_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(last_name.errors.count, "error") %> prohibited this last_name from being saved:</h2>

      <ul>
      <% last_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Jones' %>
  </div>

  <%= f.submit class: 'btn btn-success' %>

<% end %>

app/views/last_names/edit.html.erb
<div align="center">
  <h1>Editing Last Name</h1>

  <%= render 'form', last_name: @last_name %>

</div>

app/views/last_names/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Last Names</h1>
      <%= link_to 'New Last Name', new_last_name_path, class: 'btn btn-success' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h2>Name</h2>
    </div>
    <div class="col-md-6">
      <h2>Actions</h2>
    </div>
  </div>

  <% @last_names.each do |last_name| %>
  <div class="row">
    <div class="col-md-6">
      <p><%= last_name.name %></p>
    </div>
    <div class="col-md-6">
      <div class="btn-group" role="group">
        <%= link_to 'Edit', edit_last_name_path(last_name), type: 'button', class: 'btn btn-info' %>
        <%= link_to 'Destroy', last_name, method: :delete, data: { confirm: 'Are you sure?' } , type: 'button', class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/last_names/new.html.erb
<div align="center">
  <h1>New Last Name</h1>

  <%= render 'form', last_name: @last_name %>
</div>